### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by deleteselected** [koopjs/koop-app-example#53]
when I run git clone git@github.com:koopjs/koop-app-example.git

I get

Cloning into 'koop-app-example'...
Warning: Permanently added the RSA host key for IP address '140.82.113.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by haoliangyu** [comment]
A public key is required for cloning over SSH, as the ssh protocol requires authentication. If you don’t want to have a github account or don’t want to use an ssh key, you can clone over https:

git clone https://github.com/koopjs/koop-app-example.git

**Comment by haoliangyu** [comment]
I am closing this issue since it is not relevant to the repo, but GitHub. If you still have issues, googling `GitHub clone with SSH` should give you help.
